Repository LunastiaMC/SkyBlock, pull requests merged in 2023-01, with the labels that each got.

#35 Ajout du système d'île (Partie III: Création et chargement)
  src/main/java/fr/lunastia/skyblock/core/commands/economy/MoneyCommand.java
  src/main/java/fr/lunastia/skyblock/core/commands/moderation/LogsCommand.java
  src/main/java/fr/lunastia/skyblock/core/gui/island/IslandCreationGUI.java
  src/main/java/fr/lunastia/skyblock/core/listeners/PlayerListeners.java
  src/main/java/fr/lunastia/skyblock/core/manager/IslandManager.java
  src/main/java/fr/lunastia/skyblock/core/manager/Manager.java
  src/main/java/fr/lunastia/skyblock/core/manager/SessionManager.java
  src/main/java/fr/lunastia/skyblock/core/session/Hats.java
  src/main/java/fr/lunastia/skyblock/core/session/Island.java
  src/main/java/fr/lunastia/skyblock/core/session/Rank.java
  src/main/java/fr/lunastia/skyblock/core/session/server/logs/LogTypeEconomy.java
  src/main/java/fr/lunastia/skyblock/core/session/server/logs/LogTypeLogs.java
Labels: Système d'île

#33 Warps
  pom.xml
  src/main/java/fr/lunastia/skyblock/core/Core.java
  src/main/java/fr/lunastia/skyblock/core/commands/teleportation/WarpCommand.java
  src/main/java/fr/lunastia/skyblock/core/manager/Manager.java
  src/main/java/fr/lunastia/skyblock/core/manager/WarpManager.java
  src/main/java/fr/lunastia/skyblock/core/session/server/Warp.java
  src/main/resources/warps.yml
Labels: Nouveau système

#18 Ajout de la commande /kit add (non fonctionnelle)
  src/main/java/fr/lunastia/skyblock/core/Core.java
  src/main/java/fr/lunastia/skyblock/core/commands/utils/KitCommand.java
  src/main/java/fr/lunastia/skyblock/core/gui/KitGUI.java
  src/main/java/fr/lunastia/skyblock/core/manager/GUIManager.java
  src/main/java/fr/lunastia/skyblock/core/manager/KitManager.java
  src/main/java/fr/lunastia/skyblock/core/manager/Manager.java
  src/main/java/fr/lunastia/skyblock/core/session/server/Kit.java
  src/main/java/fr/lunastia/skyblock/core/utils/BukkitSerialization.java
Labels: Nouvelle commande
